# These are supported funding model platforms

github: ikegami-yukino
custom: ['https://www.paypal.me/yukinoi', 'https://www.amazon.co.jp/hz/wishlist/ls/15HRUQ0OYGJYQ?type=wishlist&filter=unpurchased&sort=priority']
